FROM ubuntu:19.04

LABEL \
  org.label-schema.schema-version="1.0" \
  org.label-schema.name="instantbox/ubuntu:19.04" \
  org.label-schema.vcs-url="https://github.com/instantbox/instantbox-images" \
  maintainer="Instantbox Team <team@instantbox.org>"

WORKDIR /home

RUN apt-get update -qq && apt-get install -qq -y python3-pip --no-install-recommends \
  && rm -rf /var/lib/apt/lists/* \
  && pip3 install freeFile

COPY ./ttyd_linux.x86_64 /usr/bin/

RUN chmod +x /usr/bin/ttyd_linux.x86_64

CMD ["ttyd_linux.x86_64", "-p", "1588", "bash"]

EXPOSE 1588

ARG BUILD_DATE
ARG VCS_REF
LABEL \
  org.label-schema.build-date=$BUILD_DATE \
  org.label-schema.vcs-ref=$VCS_REF
